language: java

jdk:
  - oraclejdk11

notifications:
  email: korzepadawid@yahoo.com

services:
  - postgresql

before_install:
  - chmod +x ./gradlew

before_script:
  - psql -c 'create database db;' -U postgres

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

jobs:
  include:
    - stage: test
      script: ./gradlew check
    - stage: report
      script: ./gradlew jacocoTestReport
    - stage: build
      script: ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)