# You need to create .env file with
# JWT_CONFIG_SECRET
# AWS_S3_ACCESS_KE
# AWS_S3_SECRET_KEY
# AWS_S3_REGION
# AWS_S3_BUCKET_NAME

version: "3"

services:
  backend:
    image: "spring-task-planner:latest"
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Warsaw
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"
  database:
    image: "postgres:latest"
    container_name: "database"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"