spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  config:
    access-token-expiration-in-seconds: 1800
